dist: xenial
language: node_js
  # ^ We don't specify the NodeJS version here because
  # it's difficult to know which number actually installs something rather
  # than resulting in an erroneous build

# Unless we specify "sudo: false", build runs in VM, not container

# Limit the number of commits it will clone
git:
  depth: 3

# Only do CI for the default branch
branches:
  only:
  - latestRelease

install:
  - nvm install node
  # ^ Use NVM to install latest node since Travis CI's docs aren't very'
  # helpful as to how to do that
  - npm i -g npm
  # Also update NPM
  - npm i -g purescript@0.13.4 spago@0.9.0 parcel
  # ^ Installing PureScript 0.13.4 now works

# Print version numbers
before_script:
  - chmod +x .travis/print-versions.sh
  - ./.travis/print-versions.sh

script:
  - spago build
  # ^ Install and compile dependencies and source code
  # before bundling and building it
  - spago docs
  # ^ Ensure that `spago docs` command will exit successfully
  - chmod +x .travis/bundle-and-build.sh
  - ./.travis/bundle-and-build.sh

cache:
  directories:
    - .spago
